version: "3.2"
services:
  projectx-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_BACKEND_BASE_URL=${VITE_BACKEND_BASE_URL}
        - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
        - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    image: ${DOCKER_IMAGE_REPO}/projectx-frontend-projectx-frontend:v3
    restart: always
    ports:
      - "8080:8080"
      # - "80:80"
      - "3000:3000"
    environment:
      VITE_BACKEND_BASE_URL: ${VITE_BACKEND_BASE_URL}
      PM2_PUBLIC_KEY: ${PM2_PUBLIC_KEY}
      PM2_SECRET_KEY: ${PM2_SECRET_KEY}
    volumes:
      - ./:/projectx-frontend
      # - ./projectx-frontend/node_modules
    
  # nginx:
  #   image: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   ports:
  #     # Local:Docker
  #     - "80:80"
  #     - "443:443"
  #   environment:
  #     - NGINX_HOST=0.0.0.0
  #     - NGINX_PORT=80
  #   links:
  #     - "projectx-frontend"